eruptivne <- c("1. Koja su dva osnovna litološka èlana radlovaèkog semimetamorfnog kompleksa?",
                       "2. Koji su benefiti eksploatacije jalovišta primjenom modernih pokretnih postrojenja za sitnjenje
                       i klasiranje?",
                       "3. Skiciraj i objasni tehnološku shemu pri radu u kompleksu pokretnih postrojenja za sitnjenje i
                       klasiranje (ukljuèujuæi pokretno postrojenja FlexRoro, pokretno postrojenja LT 110 i
                                   pokretno sito Warrior 1800).",
                       "4. Kolike su prosjeène otkopane kolièine dijabaza u Republici Hrvatskoj u razdoblju 2000. –
                       2008. godina?",
                       "5. U koju vrstu magmatskih stijena spada dijabaz?",
                       "6. Kolika je vatrootpornost kamene vune?",
                       "7. O èemu ovisi svojstvo toplinske vodljivosti materijala?",
                       "8. Kako se dobije brutto dobit trgovaèkog društva?",
                       "9. Koliki je koeficijent toplinske vodljivosti l kamene vune pri optimalnim temperaturama?",
                       "10. Koja se veziva koriste u postupku briketiranja?",
                       "11. Koje su graniène i optimalne vrijednosti sadržaja silicijevog dioksida u dijabazu kao sirovine za
                       proizvodnju kamene vune?",
                       "12. Koje mehanièke osobine kamena vuna ujedinjuje?",
                       "13. Kako su nastale efuzivne magmatske stijene?",
                       "14. Kolike su vrijednosti upijanja vode kamene vune za kraæe i dulje vrijeme?",
                       "15. Koje uvjete moraju zadovoljiti nusprodukti za postupak recikliranja (briketiranja)?",
                       "16. U kojoj kolièini i koja vrsta veziva se koristi za povezivanje vlakana kamene vune?",
                       "17. Objasni od èega u petrografskom (strukturnom) smislu potjeèu znaèajke dijabaza zbog kojih
                       je cijenjen i tražen?",
                       "18. Koji troškovi èine rashode poslovanja?",
                       "19. Gdje i pri kojoj temperaturi se odvija postupak polimerizacije kamene vune?",
                       "20. Koji je sastav grotlenih plinova pri taljenju u kupolnoj peæi?",
                       "21. U kojem rangu se kreæe gustoæa kamene vune?",
                       "22. Kolika je tlaèna èvrstoæa (pri 10% deformacije) i nosivost toèkastog parcijalnog optereæenja                       kamene vune?",
                       "23. Kako se zbrinjavaju nusproizvodi nastali u postupku proizvodnje kamene vune?",
                       "24. Koji je gubitak u postupku razvlaknavanja taline iz kupone peæi?",
                       "25. Koje su glavne tehnološke faze u proizvodnji kamene vune?",
                       "26. Kako su nastale intruzivne magmatske stijene?",
                       "27. Nacrtaj dijagram vatrootpornosti (taljenja) za razlièite izolacijske materijale.",
                       "28. Kako se pospješuje izgaranje koksa u kupolnoj peæi pri taljenju dijabaza?",
                       "29. Što su doleriti?",
                       "30. Koja dva osnovna uvjeta kvalitete treba ispuniti sirovina za proizvodnju kamene vune?",
                       "31. Koja izolacijska svojstva posjeduje kamena vuna?",
                       "32. Kako se kreæu kolièine eksploatacijskih rezervi dijabaza u Republici Hrvatskoj u razdoblju
                       2000. – 2008.?",
                        "33. Iz kojih se sirovina proizvodi mineralna vuna?",
                       "34. Koja se granulometrija dijabaza zahtjeva za proizvodnju kamene vune?",
                       "35. Koja je temeperatura taljenja kamene vune?",
                       "36. Koje su poželjne osobine koksa kao goriva pri taljenju sirovine u kupolnoj peæi?",
                       "37. Koliko iznosi godišnja eksploatacija eruptivaca u Republici Hrvatskoj u razdoblju 2000. –
                       2008.?",
                       "38. U kojim gospodarskim aspektima se ogleda znaèaj dijabaza kao mineralne sirovine?",
                       "39. Na kojoj temeperaturi se odvija proces taljenja sirovine u kupolnoj peæi?",
                       "40. Koliki je maksimalni dopušteni gubitak izgaranja pri 975 °C dijabaza kada se koristi kao                       sirovina za proizvodnju kamene vune?",
                       "41. Koje su kolièine eksploatacijskih rezervi eruptivnih stijena u Republici Hrvatskoj u 2008.
                       godini?",
                       "42. Koji glavni minerali se nalaze u dijabazu?",
                       "43. Navedi gdje se sve u tehnološkom postupku proizvodnje kamene vune stvaraju nusproizvodi?",
                       "44. Kako su nastale žiène magmatske stijene?",
                       "45. Nabroji glavne grupe ulagaèkih troškova za površinski kop?",
                       "46. Koje se prirodne sirovine (materijali) koriste u proizvodnji kamene vune?",
                       "47. Koje se sirovine koriste u proizvodnji staklene vune?",
                       "48. Nabroji koje se vrste eruptivnih stijena eksploatiraju u Republici Hrvatskoj?",
                       "49. Prema kojim kriterijima se klasificiraju magmatske (eruptivne) stijene?",
                       "50. Kako se dijele magmatske (eruptivne) stijene prema mjestu postanka?",
                       "51. U kojim uvjetima nastaju efuzivne magmatske stijene?",
                       "52. U kojim uvjetima nastaju intruzivne magmatske stijene?",
                       "53. Koja svojstva kvalificiraju dijabaz za izradu završnih, habajuæih slojeva asfalta?",
                       "54. Kojem strukturnom svojstvu se pripisuje èvrstoæa i žilavost dijabaza?",
                       "55. U kojim granicama se kreæe tlaèna èvrstoæa dijabaza?",
                       "56. Na što ukazuje pojava kuglastog luèenja (pilow lave) u ležištima dijabaza?",
                       "57. U kojim granicama mora biti sadržaj SiO2 u eruptivnoj stijeni za proizvodnju kamene vune?",
                       "58. Navedi tehnološke faze u proizvodnji kamene vune.",
                       "59. Koje se sirovine koriste u proizvodnji staklene vune?",
                       "60. Koje se sirovine koriste u proizvodnji kamene vune?",
                       "61. Koji su produkti taljenja kamenog materijala u kupolnoj peæi?",
                       "62. Opiši u glavnim crtama tehnološki postupak briketiranja pri proizvodnji kamene vune?",
                       "63. Definiraj svojstvo toplinske vodljivosti materijala.",
                       "64. Koja je vrijednost toplinske vodljivosti za kamenu vunu?")