eruptivne_odgovor <- c("Dijabazi i metaklastiti",
                       "Racionalno korištenje mineralne sirovine, eksploatacijom jalovišta smanjuje se potreba za širenjem i zauzimanjem prostora eksploatacijskim poljima, potièe se i poštiva naèelo racionalnog korištenja prostornog resursa, smanjuje se volumen jalovišta te potrebni prostor za njegovo lociranje, pokretna postrojenja prilaze jalovištu te se smanjuju transportni troškovi, nema troškova bušenja i miniranja, nema radova u otkrivci i nema potrebe za istražnim radovima.",
                       "Odminirani materijal se transportira do postrojenja za klasiranje FlexRoro gdje se materijal odvaja na klase -80 mm i +80 mm. FlexRoro je uostalom vrlo uèinkovit za razdvajanje stijene od zemlje, no ukoliko ne postoji puno zemlje u materijalu isti se ne koristi. Klasa +80 mm se dalje drobi i klasira u pokretnom postrojenju za sitnjenje i klasiranje Lokotrack LT110. Tu nastaju frakcije +120 mm, 60/120 mm i -60 mm. Frakcija -60 se zatim klasira na pokretnom situ Warrior 1800 gdje nastaju frakcije -30 mm i 30/60. Klasa 30/60 ide na daljnje klasiranje u stacionarno postrojenje.",
                       "Od 178 000 do 450 000 m3 ovisno o godini.",
                       "Dijabaz je bazièna žièna magmatska stijena.",
                       "U požarnoj zaštiti konstrukcijskih elemenata poput klima kanala, èeliènih konstrukcija, betonskih stropnih konstrukcija, cjevovoda i slièno moguæe je postiæi vatrootpornost do 180 minuta.",
                       "Ona ovisi o obujamskoj masi (omjeru mase i volumena), tj. poroznosti, o kemijskom sastavu, sadržaju vlage i temperaturi materijala.",
                       "Brutto dobit = ukupni prihodi umanjeni za troškove",
                       "Na optimalnim temperaturama kamena vuna ima koeficijent toplinske vodljivosti ??D izmeðu 0,035 i 0,040 W/mK.",
                       "Veziva u postupku briketiranja su vapno, cement, vodeno staklo i klinker. Korištenje cementa kao veziva pokazalo se kao najbolje rješenje.",
                       "Maksimalno 51 %, minimalno 47 %, a optimalno 49 % ukupne mase.",
                       "Kamena vuna kombinira mehanièke osobine kamena (èvrstoæu, visoku toèku paljenja) s osobinama koje posjeduje vuna (fleksibilnost, toplinska izolacija).",
                       "Efuzivne stijene (površinske) nastale su brzom kristalizacijom ili skrutnjavanjem lave pri niskom tlaku na površini litosfere ili blizu nje.",
                       "Upijanje vode kod kraæeg stavljanja u vodu WS<1,0 kg/m2, odnosno kod dužeg stavljanja u vodu WL(P)<3,0 kg/m2.",
                       "Za postupak recikliranja moraju ispunjavati uvjete sastava, velièine zrna, èvrstoæe i postojanosti na povišenim temperaturama. Promjer zrna mora biti 20 – 120 mm, a jednoaksijalna tlaèna èvrstoæa briketa mora iznositi najmanje 2,4 MPa.",
                       "Vezivo je smjesa fenol-formaldehidne smole, protuprašnog ulja, amonijaène vode, silana i vode u odreðenim omjerima. (1-3 % max)",
                       "Dijabaz posjeduje tipiènu dijabaznu ofitsku strukturu (struktura isprepletenih štapiæastih plagioklasa èije meðuprostore ispunjava piroksen, najèešæe augit), homogenu teksturu i agregat plagioklasa, piroksena, klorita, kvarca, opakog minerala i ostalih sastojaka. Plagioklasi se nalaze kao kratki i izduženi idiomorfni prizmatski presjeci. Dijabazna ofitska struktura uzrok je velikoj kompaktnosti dijabaza koji je jedna od najèvršæih i najžilavijih stijena uopæe.",
                       "Rashodi poslovanja: troškovi eksploatacije, plaæe, troškovi osiguranja, amortizacija.",
                       "U sušionoj komori dolazi do polimerizacije fenol-formaldehidne smole na bazi cirkulacije vruæeg zraka gdje na približno 250° C vezivo otvrdne i vuna dobije svoj konaèan oblik i tvrdoæu.",
                       "U grotlenim plinovima nalazi se 6 – 10 % ugljiènog dioksida, cca 500 mg/Nm3, sumpor (IV) oksida, cca 500 mg/Nm3 sumporovodika i prašina.",
                       "Gustoæa kamene vune: 34-165 kg/m3.",
                       "Tlaèna èvrstoæa kod 10% deformacije CS(10)=50-70 kPa, a nosivost toèkastog parcijalnog optereæenja PL(5)=500-600 kPa",
                       "Nusproizvodi se briketiraju i vraæaju u tehnološki proces proizvodnje mineralne vune.",
                       "Sva kolièina taline koja dospije na centrifugu u cilju izvlaèenja vlakana ne završi u gotovom proizvodu, veæ se jedan dio taline (cca 12%) ne razvlakna kvalitetno i padne ispod centrifuge.",
                       "1. Skladištenje sirovina i punjenje silosa dnevne potrošnje
                       2. Proces taljenja sirovina u kupolnoj peæi
                       3. Taloženje nastalih vlakana u taložnoj komori
                       4. Polimerizacija fenol-formaldehidne smole u sušionoj komori
                       5. Formatiranje proizvoda
                       6. Pakiranje proizvoda",
                       "Intruzivne stijene (dubinske) nastale su u uvjetima visokog tlaka polaganim hlaðenjem i potpunom kristalizacijom magme u dubljim dijelovima litosfere.",
                        "Pogledaj sliku",
                       "Za izgaranje koksa u kupolnu peæ se upuhuje zrak te i odreðena kolièina kisika.",
                       "Doleriti su krupnozrnasti varijeteti dijabaza tj. dijabazi izrazito krupnozrnaste dijabazne strukture.",
                       "Optimalna granulacija i kemijski sastav.",
                       "Kamena vuna je izolacijski materijal mineralnog porijekla za toplinsku, zvuènu i protupožarnu izolaciju u graditeljstvu, industriji i brodogradnji.",
                       "Najveæe su bile 2000. god. i to oko 8 770 000 m3, a najmanje 2008. god. oko 4 600 000 m3.",
                       "Za proizvodnju mineralne vune koriste se prirodni i umjetni silikatni materijali.",
                       "Najèešæe se traži dijabaz granulometrije 80/160, a u novije vrijeme i granulometrija 90/170.",
                       "Kamena vuna se topi na temperaturi veæoj od 1000°C.",
                       "Za koks je osim granulacije bitna njegova goriva vrijednost, èvrstoæa koja se iskazuje Micum indeksom, reaktivnost te sadržaj sumpora što kasnije ima efekt na sadržaj dimnih plinova koji se ispuštaju u zrak.",
                       "Kreæe se od 450 000 m3 do 1 330 000 m3, a najveæa eksploatacija bila je u 2007. god.",
                       "Dijabaz se koristi za habajuæe slojeve kod završnih slojeva cestovnih prometnica te kao sirovina za proizvodnju izolacijskih materijala (kamena vuna). ",
                       "Sirovine se u kupolnoj peæi tale na temperaturi od 1500°C.",
                       "Gubitak izgaranja pri 975 °C ne smije biti veæi od 4,5 % mase, a u stvarnosti taj gubitak treba težiti nuli.",
                       "Oko 19 165 000 m3.",
                       "Plagioklasi, augit, klorit, kvarc, opaki mineral.",
                       "Nusproizvodi nastaju u slijedeæim procesima: u fazi formiranja vlakana, rezanjem gotove kamene vune i povratom ošteæene vune iz skladišta, šljaka ispod kupolne peæi, pepeo, kamena sitnež, sitnije èestice koksa..",
                       "Žiène stijene su nastale hlaðenjem i kristalizacijom magme, lave, vruæih otopina i para utisnutih u pukotine stijena.",
                       "Rudarski radovi, strojevi i oprema, ureðenje prostora, tehnièka dokumentacija i upravni postupci.",
                       "Kamena vuna se dobiva taljenjem prirodnih mineralnih stijena eruptivnog (bazalt,dijabaz) i sedimentnog (dolomit) porijekla.",
                       "Osnovne sirovine za proizvodnju staklene vune su stakleni otpad te osnovne sirovine za proizvodnju stakla (kvarcni pijesak, vapnenac, soda,...).",
                       "Dijabaz, amfibolit, andezit, trahibazalt, granit, gnajs.",
                       "Prema sadržaju SiO2, prema mjestu postanka i mineralnom sastavu te prema glavnim mineralima.",
                       "Intruzivne, efuzivne i žiène.",
                       "Efuzivne stijene (površinske) nastaju brzom kristalizacijom ili skrutnjavanjem lave pri niskom tlaku na površini litosfere ili blizu nje.",
                       "Intruzivne stijene (dubinske) nastaju u uvjetima visokog tlaka polaganim hlaðenjem i potpunom kristalizacijom magme u dubljim dijelovima litosfere.",
                       "Velika tlaèna èvrstoæa, velika otpornost na habanje, slabo upijanje vode, postojanost na djelovanje mraza. ",
                       "Dijabazna ofitska struktura uzrok je velikoj kompaktnosti dijabaza koji je jedna od najèvršæih i najžilavijih stijena uopæe.",
                       "200-400 MPa.",
                       "Ukazuje na efuziju u vodenoj, odnosno marinskoj sredini.",
                       "47-51%, optimalno 49%.",
                       "1. Skladištenje sirovina i punjenje silosa dnevne potrošnje 
                       2. Proces taljenja sirovina u kupolnoj peæi 
                       3. Taloženje nastalih vlakana u taložnoj komori 
                       4. Polimerizacija fenol-formaldehidne smole u sušionoj komori 
                       5. Formatiranje proizvoda 
                       6. Pakiranje proizvoda",
                       "Osnovne sirovine za proizvodnju staklene vune su stakleni otpad te osnovne sirovine za proizvodnju stakla (kvarcni pijesak, vapnenac, soda,...).",
                       "Kamena vuna se dobiva taljenjem prirodnih mineralnih stijena eruptivnog (bazalt,dijabaz) i sedimentnog (dolomit) porijekla.",
                       "Procesom taljenja sirovina u kupolnoj peæi nastaje talina iz koje se dobiva kamena vuna, a na vrhu kupolne peæi izlaze grotleni (dimni) plinovi, koji su predmet procjene utjecaja na okoliš. ",
                       "Briketiranje je postupak u kojem se sitnozrni materijal dovodi u stanje visokog tlaka te se na dodirnim toèkama izmeðu zrna ostvaruju veze. Promjer zrna mora biti 20 – 120 mm, a jednoaksijalna tlaèna èvrstoæa briketa mora iznositi najmanje 2,4 MPa. U brikete se dodaje približno 15 % cementa. Voda se dodaje u kolièini od cca 50 l/t smjese. Tako pripremljen beton transportira se u grotlo automatskog vibracijskog stroja gdje se tlaèi pod tlakom od 300 bara. Na taj naèin dobiju se briketi u obliku prizme (šesterostrane ili èetverostrane), mase 1,5 do 2 kg.",
                       "Toplinska provodljivost nekog materijala definira se kolièinom topline [Q] u sekundi [s] i po kvadratnom metru [m2] koja prolazi kroz homogeni materijal debljine 1 metra [m], ukoliko temperaturna razlika izmeðu toplije i hladnije strane materijala iznosi 1 K.",
                       "Toplinska vodljivost kamene vune je vrlo niska i zato je dobar izolator. Na optimalnim temperaturama kamena vuna ima koeficijent toplinske vodljivosti ??lambdaD izmeðu 0,035 i 0,040 W/mK."                 
                       )