glina_odgovor <- c("To su prije svega hidratizirani silikati aluminija, zatim karbonati oksida, oksidi željeza i kvarc.",
                   "1.  gline kaolinitskog tipa, 
                2.  gline montmorilonitskog tipa, 
                3.  gline ilitskog tipa, 
                4.  gline kaolinitskog tipa nastaju razgradnjom granitnih stijena. ",
                   "- kaolin,  
                - lonèarska glina, 
                - ilovaèa, 
                - glineni škriljavci, 
                - laporasta glina, 
                - suknarska ili uma glina. ",
                   "- bubrenje, 
                - upijanje i zadržavanje vode, 
                - nepromoèivost i s njom u uskoj vezi plastiènost, 
                - adsorpcija drugih iona i moguænost izmjene vlastitih iona s ionima iz disperznog sredstva.",
                   "- plastiènost, 
                - ponašanja pri sušenju, 
                - ponašanja pri peèenju, 
                - sposobnosti upijanja i zadržavanja vode.",
                   "Svojstvo gline da se zamiješana s vodom pod odreðenim uvjetima (povišen tlak, temperatura) da oblikovati, pri èemu steèeni oblik trajno zadrži. ",
                   "- adsorbirana voda,
                - voda u kristalnoj rešetki u meðuslojnom prostoru,
                - voda u porama, 
                - kontinuirani filmovi vode oko èestica. ",
                   "2-10%",
                   "- iznosu ili kolièini vode koja ispari sušenjem, 
                - svojstvima i strukturi glinene mase, 
                - dimenzijama i obliku elemenata koji se suše 
                - brzini sušenja, 
                - naèinu sušenja.",
                   "- zagrijavanjem proizvoda do temperature sušenja, 
                - sušenjem kod konstantne temperature,
                - dosušivanjem u završnom periodu sušenja.",
                   "Zbog oksidacije prisutnih organskih tvari koje ako su prisutne u glinenom materijalu sagorijevaju kod ovih uvjeta i izlaze iz njega.",
                   "4 faze, 120-1250 oC.",
                   "Procesom stvaranja mulita, nastala tekuæa faza popunjava pore, èime dolazi do poveæanja gustoæe i smanjenja poroznosti materijala.",
                   "Svojstvo koje glina pokazuje kroz otpornost na mehanièka i kemijska djelovanja pod utjecajem visoke temperature. Ta svojstva karakterizira otpornost da sve do visokih temperatura ona ne omekšava. ",
                   "Lako taljive i teško taljive.",
                   "- vrlo plastiène, 
                - plastiène, 
                - slabo plastiène gline.",
                   "O specifiènoj površini glinenih èestica. Što su èestice sitnije ili finije njihova je specifièna površina veæa i veæa je moguænost upijanja vode, a time ujedno glina je i plastiènija.",
                   "SiO2, CaCO3, dolomiti, sulfati Ca i Mg, zatim željezni spojevi i alkalije te dr.",
                   "U izvjesnoj mjeri je poželjna, jer SiO2 djeluje kao sredstvo koje smanjuje skupljanje.",
                   "Prisutnost željenog oksida u izvjesnoj mjeri utjeèe na temperaturu peèenja, tj. snižava je jer spojevi željeza djeluju kao topitelji. ",
                   "Prisutnost topljivih soli je takoðer nepoželjna jer iste uzrokuje tzv. iscvjetavanje, koje se manifestira izbijanjem soli na površinu proizvoda, opeke, odnosno samoga zida izraðenog od opeke.",
                   "1. Granulometrijski sastav, 
                2. Odreðivanje vlažnosti opekarske gline, 
                3. Odreðivanje gustoæe opekarske gline, 
                4. Ispitivanje vodopropusnosti u kompresijskom permeamentu metodom promjenjivog hidrostatskog tlaka, 
                5. Proctorov pokus.",
                   "Ovim pokusom odreðuje se optimalna vlaga pri kojoj, kada se tlo zbije, ono daje maksimalnu gustoæu odnosno obujamsku težinu suhog tla za odreðenu energiju zbijanja.",
                   "Metoda s konstantnim tlakom i metoda s promjenjivim tlakom.")
                   
