glina <- c("1. Nabroji glavne minerale u glini. 3 boda",
                "2. Podjela glina prema mineralnom sastavu. 3 boda",
                "3. Podjela gline prema korištenju. 3 boda",
           "4. Koje su osnovne fizikalno-kemijske znacajke gline? 3 boda",
           "5. Koje se znacajke opekarske gline ispituju vane u proizvodnji opekarskih proizvoda? 3 boda",
           "6. Opiši svojstvo plasticnosti glina. 2 boda",
           "7. U plasticnom tijestu gline navedi kategorije prisutne vode. 4 boda",
           "8. Koliki je iznos skupljanja prilikom sušenja glinenih materijala na zraku? 1 bod",
           "9. O kojim cimbenicima ovisi skupljanje glinenih materijala prilikom sušenja? 3 boda",
           "10. Navedi faze sušenja glinenih proiuzvoda. 2 boda",
           "11. Uslijed cega dolazi do povecanje poroznosti glinenih proizvoda prilikom postupka pecenja? 2 boda",
           "12. U kojem temperaturnom rangu i kroz koliko faza se odvija proces pecenja glinenih proizvoda? 2 boda",
           "13. Uslijed cega dolazi do smanjenja poroznosti glinenih proizvoda prilikom postupka pecenja? 2 boda",
           "14. Opiši svojstvo vatrostalnosti gline? 2 boda",
           "15. Podjela glina prema vatrostalnosti? 2 boda",
           "16. Podjela glina prema svojstvu upijanja i zadravanja vode? 2 boda",
           "17. O cemu ovisi sposobnost gline za upijanje i zadravanje vode? 2 boda",
           "18. Koje primjese (minerale) sadri opekarska glina? 2 boda",
           "19. U kojem smislu kremen ima pozitivno djelovanje pri pecenju opekarskih proizvoda? 1 bod",
           "20. Kako eljezni oksid djeluje pri pecenju opekarskih proizvod? 2 boda",
           "21. Kako topljive soli djeluje pri pecenju opekarskih proizvod? 2 boda",
           "22. Koja svojstva opekarske gline je potrebno utvrditi (ispitati)? 3 boda",
           "23. Što se odreduje Proctorovim pokusom prilikom ispitivanja opekarske gline? 2 boda",
           "24. Koje su metode ispitivanja vodopropusnosti gline? 1 bod")