karbonati <- c("1. Koliko je ucešce kalcija u Zemljinoj kori?",
                "2. Kolika je teoretska a koliko stvarna (prirodna) gustoca kalcijevog karbonata?",
                "3. Iz kojeg razloga varira gustoca kalcijevog karbonata u prirodi? 2 boda", 
               "4. Od cega dolazi boja prirodnog kalcijevog karbonata? 2 boda",
               "5. Ispiši kemijske reakcije u kojima nastaje kalcijev karbonat? 3 boda",
               "6. Koji je nacin prepoznavanja kalcijevog karbonata u prirodi? 1 bod",
               "7. Kolika je topivost kalcijevog karbonata u cistoj vodi pri normalnim PT uvjetima? 1 bod",
               "8. Što utice na povecanje topivosti kalcijevog karbonata? 1 bod",
               "9. Kolika je topivost kalcijevog karbonata u vodi zasicenoj ugljicnim dioksidom? 1 bod",
               "10. U kojim jedinicama se izražava tvrdoca vode? 1 bod",
               "11. Koliko iznosi 1o tvrdoce vode u Njemackoj? 1 bod",
               "12. Uz koje procese je vezan nastanak kalcijevog karbonata? 2 boda",
               "13. Što je dijageneza? 2 boda",
               "14. Opiši proces dijageneze karbonatnih sedimenata? 3 boda",
               "15. Što je sparit? 1 bod",
               "16. Što je mikrit? 1 bod",
               "17. Što je dolomitizacija? 1 bod",
               "18. U kojim fazama može nastupiti proces dolomitizacije? 2 boda",
               "19. Opiši i objasni mehanizam utjecaja pritiska na stvaranje i razlaganje kalcijevog karbonata. 4 boda",
               "20. Opiši i objasni mehanizam utjecaja temperature na stvaranje i razlaganje kalcijevog karbonata.",
               "21. Nabroji kristalne forme kalcijevog karbonata. 2 boda",
               "22. Opiši klasifikaciju vapnencu prema sadržaju kalcijevog i magnezijevog karbonata. 3 boda",
               "23. Klasifikacija vapnenca prema cistoci. 5 boda",
               "24. Definicija punila sukladno normi DIN 55943. 3 boda",
               "25. Koji su opci kriteriji za primjenu punila? 3 boda",
               "26. Nabroji minerale koji se koriste za punila? 3 boda",
               "27. Koje su dvije osnovne primjene kalcijevog karbonata pri proizvodnji papira? 2 boda",
               "28. Koji je udio mineralnih punila u proizvodnji papira? 2 boda",
               "29. Kako abrazivnost punila djeluje u proizvodnji papira? 1 bod",
               "30. U kojim granicama se krece finoca zrna punila u proizvodnji papira? 2 boda",
               "31. Nabroji svojstva punila znacajna pri proizvodnji papira? 4 boda",
               "32. Koji minerali ucestvuju i koliko u svjetskoj proizvodnji punila i pigmenata za proizvodnju papira?",
               "33. Koliko je udio minerala u ukupnoj masi papira? 1 bod",
               "34. Koje su namjene dodavanja minerala u proizvodnji plastike? 2 boda",
               "35. Koja poboljšanja se postižu pri dodavanju punila u plastiku? 4 boda",
               "36. Kako se definira velicina oblika cestica (aspect ratio) kod punila? 1 bod",
               "37. Objasni kako oblik cestica punila djeluje na svojstva plastike? 3 boda",
               "38. U kojim se granicama krece velicina cestica punila kalcijevog karbonata za razlicite vrste plastike?",
               "39. Objasni velicinu specificne površine punila i kako djeluje na svojstva plastike. 3 boda",
               "40. Definiraj svojstvo površinske energija/naprezanja punila. 2 boda",
               "41. Objasni znacaj i mehanizam djelovanja površinske energije/naprezanja punila u plastici. 3 boda",
               "42. Što se postiže površinskim omatanjem cestice punila? 1 bod",
               "43. Kako se odnosi toplinska provodljivost mineralnih punila i polimera? 1 bod",
               "44. Kako se odnosi specificna toplina mineralnih punila i polimera? 1 bod",
               "45. Koja je svrha povecanja toplinske provodljivosti i smanjenja specificne topline plastike dodavanjem mineralnih punila? 2 boda",
               "46. Koji minerali ucestvuju i koliko u svjetskoj proizvodnji punila za plastiku? 4 boda",
               "47. Koja se poboljšanja svojstava plastike postižu korištenjem kalcijevog karbonata kao punila u proizvodnji plastike? 5 boda",
               "48. Koje osnovne funkcije imaju premazni materijali? 2 boda",
               "49. Koju zaštitu objekata moraju ostvariti premazni materijali? 3 boda",
               "50. U kojim granicama se krece sadržaj kalcijevog karbonata u pojedinim premaznim proizvodima? 2",
               "51. Nabroji najvažnija svojstva minerala pri primjeni u proširivacima? 4 boda",
               "52. Koja je uloga proširivaca u površinskim premazima? 5 bodova",
               "53. Tko ima najveci udio u proširivacima u Europi i koliki je taj udio? 1 bod",
               "54. Koje osnovne uvjete kvalitete trebaju ispuniti proširivaci? 4 boda",
               "55. Koja se svojstva proširivaca nedaju mijenjati? 2 boda",
               "56. Koja se svojstva proširivaca mogu mijenjati i na koji nacin? 3 boda",
               "57. Koje su odlika kalcijevog karbonata kao proširivaca? 6 bodova",
               "58. Koje je loše svojstvo kalcijevog karbonata kao proširivaca? 1 bod",
               "59. Cime je odredena kvaliteta tla? 3 boda",
               "60. O cemu u konacnici ovisi plodnost tla? 1 bod",
               "61. Napiši temeljne relaciju razgradnje kalcijevog karbonata u tlu? 3 boda",
               "62. O cemu ovisi brzina razlaganja karbonata u tlu? 1 bod",
               "63. U kojem su odnosu sadržaj humusa u tlu i pH vrijednost? 2 boda",
               "64. Koji je normalni sadržaj humusa u obradivom tlu? 1 bod",
               "65. Koji je normalni sadržaj humusa u livadi? 1 bod",
               "66. Koji su izvori (uzroci) prirodnog kiseljenja tla? 3 boda",
               "67. Koji su izvori (uzroci) „neprirodnog“ kiseljenja tla? 3 boda",
               "68. Koliko je normalna a koliko stvarna pH vrijednost kiše? 2 boda",
               "69. Koliki je prosjecni gubitak vapna u tlu u europskim zemljama? 1 bod",
               "70. Kolika je procjenjena godišnja potrošnja vapnenih fertilizera u tlu za Europu? 1 bod",
               "71. Koja su tri glavna podrucja primjene kalcijevog karbonata kao kemijskog reagenata u zaštiti okoliša? 3 boda",
               "72. Koji su glavni onecišcivaci zraka u postrojenjima za izgaranje? 2 boda",
               "73. Navedi postupke odsumporavanja. 3 boda",
               "74. Opiši kemijskim reakcijama mokri postupak odsumporavanja? 3 boda",
               "75. O kojim procesnim parametrima ovisi stupanj odsumporavanja dimnih plinova? 4 boda",
               "76. Kojim L/G razmjerom se može postici stupanj odsumporavanja od 90% pri koncentraciji SO2 od 3500 mg/m3. ? 1 bod",
               "77. Kojim L/G razmjerom se može postici stupanj odsumporavanja od 95%, odnosno 97%, pri koncentraciji SO2 od 3500 mg/m3.? 2 boda",
               "78. Što se postiže dodavanjem kalcijevog karbonata ili vapna u izvorišnu vodu? 2 boda",
               "79. Koja je poželjna pH vrijednost pitke vode? 1 bod",
               "80. Uslijed kojih procesa opada pH vrijednost pitke vode? 3 boda",
               "81. Cime se definira kvaliteta dodataka pitkoj vodi? 2 boda",
               "82. Kako se izvodi neutralizacija otvorenih kiselih voda? 1 bod")