karbonati_odgovor <- c("3,63 %",
                       "Teoretska gustoæa kalcita iznosi 2,71 t/m3,a stvarna varira izmeðu 2,6 t/m3 i 2,8 t/m3.",
                       "Ovisno o tome u kolikom su iznosu kalcijevi ioni u kristalnoj rešetki zamijenjeni ionima drugih metala poput željeza, mangana ili cinka.",
                       "Razlièita obojenja kalcita su posljedice zamjene iona kalcita drugim metalnim ionima poput željeza, cinka, kobalta ili mangana.",
                       "CaO + H2CO3 -> CaCO3+H2O;  Ca(OH)2 + H2CO3 -> CaCO3 + 2H2O",
                       "Reakcija sa klorovodiènom kiselinom.",
                       "13 mg/l vode.",
                       "Prisutnost ugljiènog dioksida.",
                       "U litri vode može se otopiti više od 1 grama kalcijevog karbonata.",
                       "Tvrdoæa vode izražena u stupnjevima je mjera otopljenog kalcijevog karbonata u vodi. ",
                       "1o=10 mg CaO/l",
                       "- odlaganje rastresenog materijala u slojevima,
                        - faza dijageneze.",
                       "Dijageneza je konsolidacija karbonatnih sedimenata u stijenu pritiskom ili cementacijom.",
                       "Nakon taloženja karbonati su zasiæeni vodom. Poroznost ove mase može biti i preko 90%. Pore su samo dijelom zatvorene. Voda zasiæena kalcijevim karbonatom sakuplja se u porama. Vodu istiskuje pritisak višeležeæih naslaga , a taloži se kalcit koji zatvara pore poput cementa. ",
                       "Cement krupniji od 4µm.",
                       "Kristalizirani cement u vapnencu.",
                       "Zamjena kalcijevih iona u kristalnoj rešetki magnezijevim ionima.",
                       "Proces se odvija u fazi sedimentacije ili kasnije u fazi dijageneze (sekundarna dolomitizacija).",
                       "Kada voda koja sadrži kalcij teèe finim kanalima vapnenca ili vulkanskih stijena nalazi se pod pritiskom, što poveæava parcijalni pritisak ugljiènog dioksida, tako da voda može otopiti znatno više kalcijevog karbonata. Ako takva voda izaðe na vanjsku atmosferu, pritisak pada na atmosferski, oslobaða se ugljièni dioksid, a kalcijev karbonat se taloži tvoreæi tipièna ležišta vapnenca. Kako smanjenje pritiska u vodi dovodi do taloženja kalcijevog karbonata isto tako poveæani pritisak može poveæati otapanje karbonata.",
                       "Zagrijavanjem vode bogate kalcijevim karbonatom oslobaða se ugljièni dioksid i taloži se kalcijev karbonat. Do taloženja kalcijevog karbonata može doæi i smanjenjem kolièine vode, èime se poveæava zasiæenost otopine. Do smanjenja kolièine vode može doæi isparavanjem ili smrzavanjem",
                       "Vaterit – heksagonalna forma, aragonit – ortorombna forma, kalcit – romboedarski sustav.",
                       "magnezijevi vapnenci – 5 do 20% magnezijevog karbonata
                        dolomitni vapnenci – 20 do 40% magnezijevog karbonata
                        èisti dolomiti – 40 do 46% magnezijevog karbonata",
                       "Vidi tablicu",
                       "Tvar od èestica koje su praktièki netopive u mediju u kojem se primjenjuju, i koje se koriste da poveæaju volumen, da postignu ili poboljšaju odreðena tehnièka svojstva i/ili da utjeèu na optièka svojstva.",
                       "Visoka raspoloživost, niska cijena, dobra raspoloživost u mediju primjene, visoka èistoæa, netoksiènost.",
                       "Kaolin, talk, kalcijev karbonat, magnezijev karbonat, barij i kalcijev sulfat, najveæa je svijetska proizvodnja i potražnja punila iz kalcijevog karbonata.",
                       "Kao punilo koje se dodaje u pulpu prije formiranja papira i punilo koje je glavna sastavnica premaza papira.",
                       "U novinskom papiru 0-15%, u woodfree uncoated 5-29% i u wood containing uncoated 12-38%.",
                       "Abrazivnost punila je odluèujuæa na trajnost opreme u proizvodnji papira.",
                       "Umijeæe moderne proizvodnje punila je u proizvodnji velièine èestica koje kombiniraju optimum kapaciteta  zadržavanja sa najveæim moguæim optièkim svojstvima (neprozirnost).",
                       "Abrazivnost punila, granulacija-finoæa punila, stupanj bjeline, faktor oblika, pH vrijednost, površinska energija, èistoæa, optièka svojstva.",
                       "Kaolin 42%, kalcij karbonat 32%, taložni kalcij karbonat 12%, talk 9%, ostali 5%.",
                       "Ukupni udio minerala dostiže 50% u ukupnoj masi papira.",
                       "Ojaèavajuæe tvari i punila.",
                       "Smanjuju tlaènu èvrstoæu, poveæavaju gustoæu i krutost, smanjuju toplinsko širenje, poveæavaju toplinsku provodljivost i time stabilnost konaènog proizvoda.",
                       "Odnos izmeðu duljine i debljine èestice.",
                       "Odreðuje da li dodatak djeluje kao ojaèivaè ili punilo. Dodaci koji imaju oblik èestice kugle, kocke ili kvadra djeluju kao punila i uobièajeno ne poboljšavaju mehanièka svojstva plastike. Plošne strukture i vlakna visokog faktora oblika proizvode ojaèavajuæi utijecaj u plastici (talk).",
                       "1-160 µm.",
                       "Specifièna površina izražava se u m2/g, mjera koliko je veza teoretski moguæe izmeðu lanaca polimera i dodanog materijala. Velika specifièna površina dopušta veliki broj veznih toèaka i bolja mehanièka svojstva.",
                       "Površinska energija/naprezanje izražava se u mJ/m2 ili mN/m, odgovara kolièini energije koja se mora upotrijebiti da se formira kvadratni metar površine punila. Što je èvršæi materijal potrebna površinska energija je veæa. ",
                       "Površinska energija/naprezanje odreðuje velièinu sila koja se razvijaju izmeðu pojedinih èestica. Ukoliko je razlika površinske energije/naprezanja punila i polimera prevelika, sile spreèavaju dobro miješanje. Površinska energija/naprezanja punila može se podesiti omatanjem èestica punila.",
                       "Površinsko omatanje ima za cilj ostvarenje veze izmeðu punila i matrice polimera. ",
                       "Toplinska provodljivost mineralnih punila je približno deset puta veæa od polimera. ",
                       "Specifièna toplina minerala je dvostruko manja u odnosu na polimere.",
                       "Dodatak mineralnih punila poboljšava toplinsku provodljivost i postoji linearna ovisnost sadržaja punila i vremena hlaðenja. Moguæe je znaèajno skratiti procese koji ukljuèuju zagrijavanje ili hlaðenje.",
                       "kalcijev karbonat 69%, talk 7%, kaolin 6%, taložni kalcij karbonat 3 %, ostali 15 %.",
                       "Visoke kemijske èistoæe – eliminira negativni katalitièki utjecaj na starenje polimera,
                        visoka bjelina i niski refrakcijski indeks – smanjenje skupih abrazivnih pigmenata poput titanovog oksida,
                        proizvodnja obojenih finalnih proizvoda,
                        niska abrazivnost. ",
                       "Zaštiæuju premazane objekte i daju boju i sjaj objektu.",
                       "Od primarnog je znaèaja zaštita od vremenskog utjecaja poput sunca i kiše, hladnoæe i topline, te agresivnih oneèišèivaæa atmosfere. Zaštita površina mora osigurati mehanièku zaštitu, te zaštitu od djelovanja mikroorganizama i biokemijskih utjecaja.",
                       "10-80 %.",
                       "Uz fizièka svojstva poput refrakcijskog indeksa, gustoæe, tvrdoæe i oblika èestica jedna od najvažnijih svojstva i kriterija za uporabu je finoæa èestica. Raspodjela velièina èestica, prosjeèna velièina èestica i gornji rez su od posebnog znaèaja.",
                       "- poboljšanje mehanièke strukture premaznog sloja › poveèavaju gustoæu i èvrstoæu te, smanjuju propusnost za plinove i kapilarnu vodu,
                        - poboljšavaju adheziju,
                        - poboljšavaju otpornost na abraziju i reguliraju željeni stupanj sjaja.
                        Proširivaèi takoðer poveæavaju kemijsku stabilnost premaza. Kao prirodni buferi i izmjenivaèi iona štite od korozije i kiselina. Proširivaèi imaju optièka svojstva koja djeluju na kvalitetu boje: neki minerali poveèavaju bjelinu dok drugi upijaju štetne UV zrake.",
                       "Najveæi udio ima kalcijev karbonat i taj udio iznosi preko 70 % tržišta.",
                       "Finoæa èestica, oblik èestica, relativna tvrdoæa, upijanje ulja i gustoæa, topivost u vodi i pH vrijednost, kemijska èistoæa i netoksiènost.",
                       "Gustoæa, èvrstoæa, pH i toksiènost. ",
                       "Ostala svojstva. Èestice krede i vapnenca omotane stearinom, imaju svojstva niskog upijanja ulja i poveæanu raspršivosti u bindersima i organskim otapalima. ",
                       "Netoksièan, otporan na vremenske promjene, dobre bjeline, niske gustoæe, slaba interakcija sa pigmentima, binderima i drugim sastavnicama površinskih  premaza, niski sadržaj elektrolita nisko upijanja ulja, antikorozivno djelovanje usplid alkalne pH vrijednosti, niska abrazivnost sprjeèava trošenje strojeva, dostupan u bilo kojoj velièini èestica i granulometrijskoj krivulji.",
                       "Osjetljivost na kiseline.",
                       "Kvaliteta tla je primarno odreðena sadržajem dušika, fosfora, kalija, kalcija i magnezija, ali isto tako i brojnih elementa u tragovima bez kojih nebi bilo uspješnog rasta biljaka.Odluèujuæi nije kolièina pojedine hranjive tvari, veæ njihov pravilan razmjer.",
                       "O uvjetima ravnoteže vapnenca.",
                       "CaCO3 + CO2 + H2O -> Ca(HCO3)2
                       Ca(HCO3)2 -> Ca(2+) + 2HCO(3-)",
                       "O prisustvu ugljiènog dioksida u tlu, koji nastaje u procesu razgradnje organskih tvari. ",
                       "Poveæanjem sadržaja humusa u tlu pH vrijednost opada.",
                       "Izmeðu 0 i 4 %.",
                       "Kreæe se izmeðu 0 i 15%, u bogatijim lokacijama izmeðu 15 i 30%.  ",
                       "To mogu biti organske kiseline, izluèevine korjena biljaka kada se organske tvari pretvaraju u redukcijskim uvjetima. Anorganske kiseline formiraju se mikrobiološkom pretvorbom. Konaèno postoji kisela reakcija ugljiènog dioksida prisutnog u veæim kolièinama u zraku tla. ",
                       "Dušièna gnojiva su kisela što zahtjeva dodatni tretman vapnencem za neutralizaciju. Imisija zakiseljavanja tla uslijed djelovanja kiselih kiša ne smije se podcijeniti.",
                       "Normalna pH iznosi 5,6 a, stvarna pH vrijednost kiše je niža za 1 do 2 pH.",
                       "250 do 350 kg CaO/ha godišnje.",
                       "10 miliona tona.",
                       "Postupak odsumporavanja dimnih plinova, priprema pitke vode, neutralizacija zakiseljenih jezera i rijeka.",
                       "Sumporni dioksid SO2, dušièni oksidi NOx i ozon O3.",
                       "Suhi postupak sa vapnom, postupak prskanjem primjenom vapna ili vapnenog hidroksida, mokri postupak temeljen na vapnu, vapnencu ili kredi sa hidroksidom gipsa.",
                       "CaCO3 + 0,5 H2O + SO2 <-> CaSO3*0,5H2O + CO2
                        CaCO3 + 2H2O + SO3 <-> CaSO4* 2H2O + CO2",
                       "Koncentraciji dimnih plinova, raspodjeli tekuæine za pranje, vremenu boravka tekuæine za pranje i dimnih plinova u èistaèu, pH vrijednosti i posebice razmjeru tekuæina za pranje/dimni plin.",
                       "L/G razmjer od 8 l/m3.",
                       "Za 95%- L/G razmjer na 14 l/m3, za 97% na 20 l/m3.",
                       "Podešava se ravnoteža vapna i ugljiènog dioksida u cilju sprjeèavanja otapanja nepoželjnih supstanci u vodovodnoj mreži i neutralizaciju kiselosti.",
                       "Izmeðu 6,5 i 9,5.",
                       "Denitrifikacije, poveæanom sadržaju ugljiènog dioksida u tlima, ispiranja nitrata i poveæanom sadržaju dušiènih i sumpornih oksida u kišnici.",
                       "Po sadržaju aktivnih komponenti i po sadržaju potencijalno štetnih sastojaka poput olova ili kadmija.",
                       "Dodavanjem kalcijevog karbonata u vode.")
                       
                       
                       