pijesci <- c("1. U kojim relacijama se krecu godišnje otkopane kolicine kremenih pijesaka u Republici Hrvatskoj u zadnjem desteljecu ? 2 boda",
                "2. Nabroji glavne primjene kremenih pijeska. 3 boda",
           "3. Navedi glavne uvjete kvalitete kremenog pijeska za primjenu u industriji? 3 boda",
           "4. Nabroji korisne minerale koji se mogu pojaviti unutar kremenih pijesaka? 2 boda",
           "5. Koji su glavni oplemenjivacki postupci koji se danas primjenjuju na kremenim pijescima? 3 boda",
           "6. Podjela ležišta kremenog pijeska u republici Hrvatskoj po postanku? 4 boda",
           "7. Podjela kremenog pijeska obzirom na velicinu zrna.3 boda",
           "8. Koji su minerali nepoželjni u kremenom pijesku kada se koristi za proizvodnju stakla? 2 boda",
           "9. Koliki je minimalni sadržaj kremena (kvarca) u kremenom pijesku za proizvodnju stakla sukladno hrvatskim normama? 1 bod",
           "10. Koliki je minimalni sadržaj željeznog oksida u kremenom pijesku za proizvodnju stakla sukladno hrvatskim normama? 1 bod",
           "11. Koliki je minimalni sadržaj klase 0,315/0,1 u kremenom pijesku za proizvodnju stakla sukladno hrvatskim normama? 1 bod",
           "12. Koliki je minimalni sadržaj kremena (kvarca) u kremenom pijesku za proizvodnju ravnog stakla sukladno americkim normama? 1 bod",
           "13. Koliki je minimalni sadržaj kremena (kvarca) u kremenom pijesku za proizvodnju ambalažnog stakla sukladno americkim normama? 1 bod",
           "14. Koliki je minimalni sadržaj kremena (kvarca) u kremenom pijesku kada se koristi kao ljevaonicki pijesak? 1 bod",
           "15. Koje su bitne znacajke kremenog pijeska kakda se koristi za ljevanje? 3 boda",
           "16. Za izradu cega se koristi kremeni pijesak u ljevaonicama? 1 bod",
           "17. Koje znacajke kremenog pijeska uticu na njegovu propusnost? 2 boda",
           "18. Koje znacajke posebice kvalificiraju kremeni pijesakpri uporabi kao punila? 1 bod",
           "19. Koliki je minimalni sadržaj željeznog oksida u kremenom pijesku za korištenje u punilima sukladno americkim normama? 1 bod",
           "20. Koja je primjena finog odnosno grubog kremenog pijeska kada se koristi kao sredstvo za cišcenje? 2 boda",
           "21. Zašto se koriste podupiraci (proppant)? 1 bod",
           "22. Prema kojim znacajkama se dijele podupiraci? 2 boda",
           "23. Do koje dubine i obzirom na koje ograanicenje se kremeni pijesak može koristiti kao podupirac u naftnim/plinskim bušotinama? 2 bod",
           "24. Koji su uvjeti kvalitete (znacajke) kremnog pijeska važne u filtraciji vode? 2 boda",
           "25. Kako oblik zrna kremenog pijeska utice na postupak filtracije? 2 boda",
           "26. Koliki je minimalni sadržaj kremena (kvarca) u kremenom pijesku, sukladno americkim normama, kada se koristi za filtraciju vode? 1 bod",
           "27. Da li se rovni kremeni pijesak iz ležištia Republike Hrvatske može koristiti za industrijsku primjenu i zašto? 3 boda",
           "28. O kojim cimbenicima ovisi ucinkovitost postupka oplemenjivanja kremenog pijeska? 3 boda",
           "29. Koji se ciljevi žele postici oplemenjivanjem kremenog pijeska? 3 boda",
           "30. Što se postiže atricijskim cišcenjem i na koji nacin? 2 boda")