pijesci_odgovor <- c("80 000-320 000 t (2010., 2005.)",
                     "Kremeni pijesak ima široku primjenu u razlièitim industrijskim granama: za proizvodnju stakla, u ljevaonièkoj industriji, za punila u proizvodnji boja i premaza, za filtraciju vode, u industriji graðevinskog materijala i dr.",
                     "Èistoæa (visoki sadržaj SiO2), niski sadržaj neèistoæa (posebice željeznih oksida) i granulometrijski sastav.",
                     "Tinjac, cirkon, rutil, granat, apatit, turmalin i dr.",
                     "Pranje, mehanièko i kemijsko atricijsko  èišæenje, flotacija, magnetska i elektrostatièka separacija, te gravitacijska koncentracija.   ",
                     "- sedimenta ležišta pijeska i pješèenjaka, 
                - silicijske stijene razvijene u karbonatnim naslagama, 
                - kvartarni kremeni pijesci eolskog podrijetla i 
                - pegmatitne žice",
                     "1. sitni pijesak (klasa 0,25/0,1 mm), 
                2. srednje krupni pijesak (klasa 0,5/0,25 mm), 
                3. krupni pijesak (klasa + 0,5 mm ili 2/0,5 mm)  ",
                     "Al2O3, Fe2O3, TiO2, Cr2O3, CaO, MgO, Na2O, K2O.",
                     "95%",
                     "5x10-5%",
                     "90%",
                     "99,5%",
                     "98,5%",
                     "98%",
                     "Oblik zrna, granulometrijski sastav, temeljna propusnost, toèka sinteriranja, udio gline i mineraloški sastav.",
                     "Kalupa i jezgri za ljevanje metala.",
                     "Velièine i oblik zrna.",
                     "Kemijska stabilnost i inertnost.",
                     "0,10% max.",
                     "Grubi pijesak obièno se primjenjuje kod  èišæenja željeznih ili  èeliènih struktura, ali i za uklanjanje tankih premaza neželjenih materijala sa površine. Fini pijesak koristi se za poliranje površina i èišæenje mekših legura poput mjedi i aluminija. U industriji odjeæe koristi se za „kameno pranje“ radne odjeæe od trapera.",
                     "Kako bi održali otvorene pukotine u stijeni i poveæali protok prirodnog plina ili nafte. ",
                     "Sukladno pritisku koji mogu podnijeti ili prema prolazu kroz odreðenu velièinu otvora sita.",
                     "Do 2450 m dubine.",
                     "Ujednaèeni oblik i granulometrijski sastav zrna. ",
                     "Okrugla zrna su znaèajna zbog protoka, dok uglata zrna imaju sposobnost zadržavanja neèistoæa. Previše uglata zrna pak mogu zaustaviti i sprijeèiti protok.",
                     "99,3%",
                     "Rovni kremeni pijesak iz naših ležišta ima ogranièenu industrijsku primjenu. Prosjeèni sadržaj SiO2 u kremenim pijescima eksploatacijskih polja u Republici Hrvatskoj kreæe se od 84% do 94%. Buduæi u proizvodnji stakla prosjeèni sadržaj SiO2 mora iznositi preko 95% razvidno je da nijedno ležište ne zadovoljava te uvjete. Osim kod proizvodnje stakla, rovni kremeni pijesak iz naših  ležišta ne može se upotrebljavati ni kao ljevaonièki pijesak za izradu kalupa i jezgri jer sadržaj SiO2  mora biti minimalno 98%, a ni kao pijesak za filtraciju jer sadržaj SiO2  mora biti minimalno 96%.",
                     "- znaèajkama rovnog pijeska, odnosno o sadržaju i vrsti štetnih primjesa u pijesku, 
                - znaèajkama primijenjenih oplemenjivaèkih postupaka i opreme 
                - postavljenim zahtjevima za kvalitetom koncentrata.",
                     "- postizanje potrebnog granulometrijskog sastava,                                                                                              
                - poveæanje sadržaja SiO2,                                                                                                                               
                - smanjenje sadržaja nepoželjnih komponenti koje snižavaju kvalitetu proizvoda  ",
                     "Atricijsko  èišæenje je proces u kojem se neèistoæe vezane za površinu zrna odstranjuju s površine uslijed abrazije prouzroèene intenzivnim trenjem tj. meðusobnim trljanjem zrna. ")
                     
                     
                     